#!/bin/bash
set -e

# =============================================================================
# deploy.sh - Déploiement local (exécuté directement sur le serveur)
# Usage: ./deploy.sh [command]
# Commands: setup, deploy, start, stop, restart, logs, status, backup
# =============================================================================

COMPOSE_FILE="docker-compose.prod.yml"
ENV_FILE=".env.prod"
PROJECT_NAME="cv-adapter"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log()  { echo -e "${CYAN}[DEPLOY]${NC} $1"; }
ok()   { echo -e "${GREEN}[OK]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
err()  { echo -e "${RED}[ERROR]${NC} $1"; }

# --- Init interactif (.env.prod) ---
cmd_init() {
  log "Configuration initiale du projet"

  if [ -f "$ENV_FILE" ]; then
    warn "$ENV_FILE existe déjà. Écraser ? (y/N)"
    read -r answer
    [[ "$answer" != "y" && "$answer" != "Y" ]] && { log "Annulé."; exit 0; }
  fi

  echo ""
  read -p "PostgreSQL user [postgres]: " PG_USER
  PG_USER=${PG_USER:-postgres}

  read -sp "PostgreSQL password: " PG_PASS
  echo ""

  read -p "JWT Secret (min 32 chars): " JWT_SEC

  if [ ${#JWT_SEC} -lt 32 ]; then
    err "JWT Secret doit faire au moins 32 caractères"
    exit 1
  fi

  read -p "Admin email [admin@example.com]: " ADMIN_EMAIL
  ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}

  read -sp "Admin password: " ADMIN_PASS
  echo ""

  cat > "$ENV_FILE" <<EOF
# Production environment - generated by deploy.sh init
POSTGRES_USER=$PG_USER
POSTGRES_PASSWORD=$PG_PASS
JWT_SECRET=$JWT_SEC
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=$ADMIN_PASS
APP_DATABASE_URL=postgresql://$PG_USER:$PG_PASS@postgres:5432/app
UNIFIED_PORT=3010
NODE_ENV=production
EOF

  ok "$ENV_FILE créé"
}

# --- Setup (pull + build) ---
cmd_setup() {
  log "Setup du projet..."

  if [ ! -f "$ENV_FILE" ]; then
    err "$ENV_FILE manquant. Lancez d'abord: ./deploy.sh init"
    exit 1
  fi

  # Créer le réseau Docker si nécessaire
  docker network inspect proxy-network >/dev/null 2>&1 || {
    log "Création du réseau proxy-network..."
    docker network create proxy-network
  }

  log "Build des images Docker..."
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" build

  ok "Setup terminé"
}

# --- Deploy (pull + build + restart) ---
cmd_deploy() {
  log "Déploiement en cours..."

  if [ ! -f "$ENV_FILE" ]; then
    err "$ENV_FILE manquant. Lancez d'abord: ./deploy.sh init"
    exit 1
  fi

  # Backup avant deploy
  cmd_backup

  log "Pull des dernières modifications..."
  git pull origin main

  log "Build des images..."
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" build

  log "Redémarrage des services..."
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d --force-recreate --remove-orphans

  # Nettoyage
  docker image prune -f >/dev/null 2>&1

  ok "Déploiement terminé"
  cmd_status
}

# --- Start ---
cmd_start() {
  log "Démarrage des services..."
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" up -d
  ok "Services démarrés"
  cmd_status
}

# --- Stop ---
cmd_stop() {
  log "Arrêt des services..."
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" down
  ok "Services arrêtés"
}

# --- Restart ---
cmd_restart() {
  log "Redémarrage des services..."
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" restart
  ok "Services redémarrés"
  cmd_status
}

# --- Logs ---
cmd_logs() {
  local service="${2:-}"
  if [ -n "$service" ]; then
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" logs -f "$service"
  else
    docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" logs -f
  fi
}

# --- Status ---
cmd_status() {
  log "État des services :"
  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" ps
}

# --- Backup ---
cmd_backup() {
  local BACKUP_DIR="./backups"
  local TIMESTAMP=$(date +%Y%m%d_%H%M%S)
  local BACKUP_FILE="$BACKUP_DIR/backup_${TIMESTAMP}.sql.gz"

  mkdir -p "$BACKUP_DIR"

  log "Backup de la base de données..."

  docker compose -f "$COMPOSE_FILE" --env-file "$ENV_FILE" exec -T postgres \
    pg_dumpall -U "${POSTGRES_USER:-postgres}" | gzip > "$BACKUP_FILE" 2>/dev/null

  if [ -s "$BACKUP_FILE" ]; then
    ok "Backup créé : $BACKUP_FILE ($(du -h "$BACKUP_FILE" | cut -f1))"
  else
    warn "Backup vide ou échoué (la base n'est peut-être pas démarrée)"
    rm -f "$BACKUP_FILE"
  fi

  # Rotation : garder les 10 derniers
  local count=$(ls -1 "$BACKUP_DIR"/backup_*.sql.gz 2>/dev/null | wc -l)
  if [ "$count" -gt 10 ]; then
    ls -1t "$BACKUP_DIR"/backup_*.sql.gz | tail -n +11 | xargs rm -f
    log "Rotation : anciens backups supprimés (garde 10)"
  fi
}

# --- Help ---
cmd_help() {
  echo ""
  echo "Usage: ./deploy.sh [command]"
  echo ""
  echo "Commands:"
  echo "  init      Configuration initiale (.env.prod)"
  echo "  setup     Build des images Docker"
  echo "  deploy    Pull + build + restart (avec backup)"
  echo "  start     Démarrer les services"
  echo "  stop      Arrêter les services"
  echo "  restart   Redémarrer les services"
  echo "  logs      Voir les logs (optionnel: nom du service)"
  echo "  status    État des services"
  echo "  backup    Backup de la base de données"
  echo ""
}

# --- Main ---
case "${1:-help}" in
  init)    cmd_init ;;
  setup)   cmd_setup ;;
  deploy)  cmd_deploy ;;
  start)   cmd_start ;;
  stop)    cmd_stop ;;
  restart) cmd_restart ;;
  logs)    cmd_logs "$@" ;;
  status)  cmd_status ;;
  backup)  cmd_backup ;;
  *)       cmd_help ;;
esac
